-- ============================================================
--  FitTrack — datos iniciales (catálogos)
--  Generado con: npm run sql   (no lo edites a mano)
--  Ejecútalo DESPUÉS de esquema.sql (o de migracion-onboarding.sql si tu base ya existía).
--  Borra y vuelve a cargar los catálogos (los datos de los usuarios no se tocan).
-- ============================================================

truncate public.ejercicios, public.recetas, public.consejos restart identity;

insert into public.ejercicios (nombre, grupo, nivel, objetivos, fase, descripcion, equipo, musculos) values
  ('Movilidad de hombros', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Círculos amplios con los brazos, 10 hacia adelante y 10 hacia atrás.', 'ninguno', 'Hombros · Espalda alta'),
  ('Rotación de cadera', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Manos en la cintura, dibuja círculos grandes con la cadera.', 'ninguno', 'Cadera · Zona lumbar'),
  ('Marcha en el sitio', 'cardio', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Eleva las rodillas a ritmo suave y mueve los brazos.', 'ninguno', 'Piernas · Corazón'),
  ('Sentadilla con brazos arriba', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Baja lento a media sentadilla estirando los brazos al techo.', 'ninguno', 'Piernas · Hombros · Core'),
  ('Gato-camello', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'En cuatro apoyos, arquea y redondea la espalda despacio.', 'ninguno', 'Columna · Core'),
  ('Sentadilla', 'piernas', 1, 'grasa,musculo,resistencia', 'principal', 'Pies al ancho de hombros, baja como si te sentaras y sube empujando el suelo.', 'ninguno', 'Cuádriceps · Glúteos · Core'),
  ('Zancada alterna', 'piernas', 1, 'grasa,musculo,resistencia', 'principal', 'Da un paso largo al frente y baja la rodilla de atrás casi al suelo. Alterna.', 'ninguno', 'Cuádriceps · Glúteos · Equilibrio'),
  ('Puente de glúteo', 'piernas', 1, 'musculo,resistencia,movilidad', 'principal', 'Boca arriba, rodillas dobladas, eleva la cadera apretando glúteos.', 'ninguno', 'Glúteos · Isquiotibiales'),
  ('Sentadilla sumo con pausa', 'piernas', 2, 'musculo,resistencia', 'principal', 'Pies muy abiertos, baja y aguanta 2 segundos abajo.', 'ninguno', 'Aductores · Glúteos · Cuádriceps'),
  ('Sentadilla con salto', 'piernas', 2, 'grasa,resistencia', 'principal', 'Sentadilla normal y sube con un salto explosivo. Aterriza suave.', 'ninguno', 'Cuádriceps · Glúteos · Pantorrillas'),
  ('Zancada búlgara (en silla)', 'piernas', 2, 'musculo', 'principal', 'Pie de atrás apoyado en una silla, baja con la pierna de adelante.', 'casa', 'Cuádriceps · Glúteos'),
  ('Sentadilla a una pierna (pistol asistida)', 'piernas', 3, 'musculo', 'principal', 'Apóyate en una pared o marco de puerta y baja en una sola pierna.', 'casa', 'Cuádriceps · Glúteos · Equilibrio'),
  ('Zancada con salto', 'piernas', 3, 'grasa,resistencia', 'principal', 'Desde zancada, salta y cambia de pierna en el aire.', 'ninguno', 'Cuádriceps · Glúteos · Potencia'),
  ('Sentadilla isométrica en pared', 'piernas', 1, 'musculo,resistencia', 'principal', 'Espalda contra la pared, rodillas a 90°, aguanta.', 'casa', 'Cuádriceps · Glúteos'),
  ('Flexiones con rodillas', 'empuje', 1, 'grasa,musculo,resistencia', 'principal', 'Rodillas en el suelo, cuerpo recto, baja el pecho al piso.', 'ninguno', 'Pecho · Tríceps · Hombros'),
  ('Flexiones inclinadas (en mesa)', 'empuje', 1, 'musculo,resistencia', 'principal', 'Manos en una mesa firme, cuerpo recto, baja el pecho al borde.', 'casa', 'Pecho · Tríceps · Hombros'),
  ('Flexiones', 'empuje', 2, 'grasa,musculo,resistencia', 'principal', 'Manos bajo los hombros, cuerpo en tabla, pecho casi al suelo.', 'ninguno', 'Pecho · Tríceps · Hombros · Core'),
  ('Fondos en silla', 'empuje', 2, 'musculo', 'principal', 'Manos en el borde de una silla detrás de ti, dobla codos y sube.', 'casa', 'Tríceps · Hombros'),
  ('Flexiones pica (hombro)', 'empuje', 2, 'musculo', 'principal', 'Cadera arriba en forma de V invertida, baja la cabeza hacia el suelo.', 'ninguno', 'Hombros · Tríceps'),
  ('Flexiones diamante', 'empuje', 3, 'musculo', 'principal', 'Manos juntas formando un rombo bajo el pecho.', 'ninguno', 'Tríceps · Pecho'),
  ('Flexiones explosivas', 'empuje', 3, 'grasa,musculo', 'principal', 'Empuja fuerte para que las manos se despeguen del suelo.', 'ninguno', 'Pecho · Tríceps · Potencia'),
  ('Superman', 'tiron', 1, 'musculo,resistencia,movilidad', 'principal', 'Boca abajo, eleva brazos y piernas a la vez y baja lento.', 'ninguno', 'Zona lumbar · Glúteos · Espalda'),
  ('Remo con toalla en puerta', 'tiron', 1, 'musculo', 'principal', 'Toalla atada a la manija de una puerta cerrada, inclínate atrás y tira.', 'casa', 'Espalda · Bíceps'),
  ('Nadador (brazos Y-T-W)', 'tiron', 2, 'musculo,movilidad', 'principal', 'Boca abajo, dibuja las letras Y, T y W con los brazos elevados.', 'ninguno', 'Espalda alta · Hombros'),
  ('Remo invertido bajo mesa', 'tiron', 3, 'musculo', 'principal', 'Acostado bajo una mesa firme, agarra el borde y sube el pecho.', 'casa', 'Espalda · Bíceps · Core'),
  ('Plancha', 'core', 1, 'musculo,resistencia,movilidad', 'principal', 'Antebrazos en el suelo, cuerpo recto, abdomen apretado.', 'ninguno', 'Core · Hombros'),
  ('Bicho muerto (dead bug)', 'core', 1, 'musculo,movilidad', 'principal', 'Boca arriba, estira brazo y pierna contrarios sin despegar la espalda.', 'ninguno', 'Core profundo'),
  ('Crunch abdominal', 'core', 1, 'grasa,musculo', 'principal', 'Boca arriba, eleva los hombros contrayendo el abdomen.', 'ninguno', 'Abdomen'),
  ('Escaladores', 'core', 2, 'grasa,resistencia', 'principal', 'En posición de flexión, lleva rodillas al pecho rápido y alterno.', 'ninguno', 'Core · Hombros · Cardio'),
  ('Plancha lateral', 'core', 2, 'musculo,resistencia', 'principal', 'De lado sobre un antebrazo, cadera alta. Cambia de lado a la mitad.', 'ninguno', 'Oblicuos · Core'),
  ('Bicicleta abdominal', 'core', 2, 'grasa,musculo', 'principal', 'Codo hacia rodilla contraria alternando, piernas en el aire.', 'ninguno', 'Abdomen · Oblicuos'),
  ('Hollow hold', 'core', 3, 'musculo,resistencia', 'principal', 'Boca arriba, brazos y piernas estirados y elevados, espalda pegada.', 'ninguno', 'Core profundo · Abdomen'),
  ('Plancha con toque de hombro', 'core', 2, 'musculo,resistencia', 'principal', 'En posición de flexión, toca el hombro contrario sin mover la cadera.', 'ninguno', 'Core · Hombros · Estabilidad'),
  ('Jumping jacks', 'cardio', 1, 'grasa,resistencia', 'principal', 'Salta abriendo piernas y brazos, vuelve a cerrar.', 'ninguno', 'Cuerpo completo · Cardio'),
  ('Rodillas arriba', 'cardio', 1, 'grasa,resistencia', 'principal', 'Trota en el sitio subiendo las rodillas a la altura de la cadera.', 'ninguno', 'Piernas · Core · Cardio'),
  ('Boxeo de sombra', 'cardio', 1, 'grasa,resistencia', 'principal', 'Golpes rápidos al aire con guardia alta, mueve los pies.', 'ninguno', 'Hombros · Core · Cardio'),
  ('Skater (patinador)', 'cardio', 2, 'grasa,resistencia', 'principal', 'Salta de lado a lado cayendo en una pierna.', 'ninguno', 'Glúteos · Piernas · Cardio'),
  ('Burpees', 'cardio', 2, 'grasa,resistencia', 'principal', 'Agáchate, lleva los pies atrás, vuelve y salta con los brazos arriba.', 'ninguno', 'Cuerpo completo · Cardio'),
  ('Burpee con flexión', 'cardio', 3, 'grasa,resistencia', 'principal', 'Burpee completo añadiendo una flexión abajo.', 'ninguno', 'Cuerpo completo · Pecho · Cardio'),
  ('Saltos de tijera rápidos', 'cardio', 3, 'grasa,resistencia', 'principal', 'Alterna pierna adelante y atrás saltando lo más rápido posible.', 'ninguno', 'Piernas · Cardio'),
  ('Saludo al sol', 'movilidad', 1, 'movilidad', 'principal', 'Secuencia fluida: brazos arriba, flexión al frente, plancha, cobra y vuelta.', 'ninguno', 'Cuerpo completo · Columna'),
  ('Estocada con rotación', 'movilidad', 1, 'movilidad', 'principal', 'En zancada baja, gira el torso hacia la pierna de adelante.', 'ninguno', 'Cadera · Columna torácica'),
  ('Perro boca abajo a cobra', 'movilidad', 1, 'movilidad', 'principal', 'Pasa lento de V invertida a pecho abierto con cadera abajo.', 'ninguno', 'Columna · Isquiotibiales · Hombros'),
  ('Sentadilla profunda sostenida', 'movilidad', 2, 'movilidad', 'principal', 'Baja al fondo de la sentadilla, codos empujan las rodillas hacia afuera.', 'ninguno', 'Cadera · Tobillos'),
  ('Rotación torácica en 4 apoyos', 'movilidad', 1, 'movilidad', 'principal', 'Mano en la nuca, abre el codo hacia el techo siguiendo con la mirada.', 'ninguno', 'Columna torácica · Hombros'),
  ('Puente con extensión de pierna', 'movilidad', 2, 'movilidad,musculo', 'principal', 'En puente de glúteo, estira una pierna manteniendo la cadera alta.', 'ninguno', 'Glúteos · Core'),
  ('Estiramiento de cuádriceps', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'De pie, lleva el talón al glúteo. Cambia de pierna a la mitad.', 'ninguno', 'Cuádriceps'),
  ('Estiramiento de isquios', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'Sentado, piernas estiradas, lleva el pecho hacia las rodillas.', 'ninguno', 'Isquiotibiales · Zona lumbar'),
  ('Postura del niño', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'De rodillas, siéntate en los talones y estira los brazos al frente.', 'ninguno', 'Espalda · Cadera'),
  ('Estiramiento de pecho en pared', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'Antebrazo en la pared y gira el cuerpo hacia el lado contrario.', 'casa', 'Pecho · Hombros'),
  ('Respiración profunda', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'Inhala 4 segundos, sostén 4, exhala 6. Relaja los hombros.', 'ninguno', 'Diafragma · Relajación'),
  ('Prensa de piernas', 'piernas', 1, 'grasa,musculo,resistencia', 'principal', 'Espalda pegada al respaldo, baja la plataforma hasta 90° y empuja con todo el pie.', 'gimnasio', 'Cuádriceps · Glúteos'),
  ('Sentadilla goblet con mancuerna', 'piernas', 1, 'grasa,musculo,resistencia', 'principal', 'Mancuerna pegada al pecho, codos adentro, baja profundo con la espalda recta.', 'gimnasio', 'Cuádriceps · Glúteos · Core'),
  ('Peso muerto rumano con mancuernas', 'piernas', 2, 'musculo,resistencia', 'principal', 'Rodillas suaves, lleva la cadera atrás bajando las mancuernas pegadas a las piernas.', 'gimnasio', 'Isquiotibiales · Glúteos · Zona lumbar'),
  ('Extensión de cuádriceps en máquina', 'piernas', 1, 'musculo', 'principal', 'Sentado, estira las rodillas hasta arriba y baja lento en 3 segundos.', 'gimnasio', 'Cuádriceps'),
  ('Curl femoral en máquina', 'piernas', 1, 'musculo', 'principal', 'Boca abajo, lleva los talones hacia los glúteos sin despegar la cadera.', 'gimnasio', 'Isquiotibiales'),
  ('Press de banca con mancuernas', 'empuje', 1, 'musculo,grasa', 'principal', 'Acostado en el banco, baja las mancuernas al pecho y empuja hacia arriba.', 'gimnasio', 'Pecho · Tríceps · Hombros'),
  ('Press militar con mancuernas', 'empuje', 2, 'musculo', 'principal', 'De pie, abdomen firme, empuja las mancuernas desde los hombros hasta arriba.', 'gimnasio', 'Hombros · Tríceps'),
  ('Jalón al pecho en polea', 'tiron', 1, 'musculo,resistencia', 'principal', 'Sentado, baja la barra hacia el pecho llevando los codos hacia las costillas.', 'gimnasio', 'Dorsales · Bíceps'),
  ('Remo sentado en polea', 'tiron', 1, 'musculo,resistencia', 'principal', 'Espalda recta, tira del agarre hacia el ombligo y junta las escápulas.', 'gimnasio', 'Espalda media · Bíceps'),
  ('Face pull en polea', 'tiron', 2, 'musculo,movilidad', 'principal', 'Polea a la altura de la cara, tira de la cuerda abriendo los codos hacia atrás.', 'gimnasio', 'Hombro posterior · Espalda alta'),
  ('Crunch en polea alta', 'core', 2, 'musculo', 'principal', 'De rodillas frente a la polea, flexiona el tronco llevando los codos a los muslos.', 'gimnasio', 'Abdomen'),
  ('Pallof press en polea', 'core', 1, 'musculo,resistencia,movilidad', 'principal', 'De lado a la polea, estira los brazos al frente sin dejar que el cuerpo gire.', 'gimnasio', 'Core · Oblicuos'),
  ('Swing con kettlebell', 'cardio', 2, 'grasa,resistencia', 'principal', 'Bisagra de cadera y empuja fuerte para que la pesa suba hasta el pecho.', 'gimnasio', 'Glúteos · Isquiotibiales · Cardio'),
  ('Sprints en bicicleta estática', 'cardio', 1, 'grasa,resistencia', 'principal', 'Pedalea a máxima velocidad con resistencia media durante todo el intervalo.', 'gimnasio', 'Piernas · Cardio'),
  ('Remo en máquina', 'cardio', 1, 'grasa,resistencia', 'principal', 'Empuja con las piernas, luego inclina el tronco y tira del mango al pecho.', 'gimnasio', 'Cuerpo completo · Cardio'),
  ('Caminata inclinada en cinta', 'cardio', 1, 'grasa,resistencia', 'principal', 'Cinta con inclinación alta, paso firme y sin agarrarte de las barras.', 'gimnasio', 'Glúteos · Pantorrillas · Cardio'),
  ('Jumping jacks suaves', 'cardio', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Saltos abriendo y cerrando piernas a ritmo cómodo, sin forzar.', 'ninguno', 'Cuerpo completo · Corazón'),
  ('Balanceo de piernas', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Apoyado en una pared, balancea una pierna adelante y atrás. Cambia a la mitad.', 'casa', 'Cadera · Isquiotibiales'),
  ('Rotación de tronco de pie', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'calentamiento', 'Pies firmes, gira el tronco a un lado y al otro dejando que los brazos sigan.', 'ninguno', 'Columna · Oblicuos'),
  ('Zancada inversa', 'piernas', 1, 'grasa,musculo,resistencia', 'principal', 'Da un paso largo hacia atrás y baja la rodilla casi al suelo. Alterna.', 'ninguno', 'Glúteos · Cuádriceps'),
  ('Elevación de talones', 'piernas', 1, 'musculo,resistencia', 'principal', 'De pie, sube en puntas de pie lo más alto que puedas y baja lento.', 'ninguno', 'Pantorrillas'),
  ('Sentadilla con pulso', 'piernas', 2, 'grasa,musculo,resistencia', 'principal', 'Baja a sentadilla y haz pequeños rebotes abajo sin subir del todo.', 'ninguno', 'Cuádriceps · Glúteos'),
  ('Subida a escalón (step-up)', 'piernas', 1, 'grasa,musculo,resistencia', 'principal', 'Sube a un escalón o silla firme con una pierna y baja controlado. Alterna.', 'casa', 'Cuádriceps · Glúteos'),
  ('Patada de glúteo en 4 apoyos', 'piernas', 1, 'musculo,resistencia,movilidad', 'principal', 'En cuatro apoyos, lleva una pierna doblada hacia el techo apretando el glúteo.', 'ninguno', 'Glúteos'),
  ('Sentadilla cosaca', 'piernas', 3, 'musculo,movilidad', 'principal', 'Piernas muy abiertas, baja hacia un lado con la otra pierna estirada. Alterna.', 'ninguno', 'Aductores · Glúteos · Cuádriceps'),
  ('Puente de glúteo a una pierna', 'piernas', 2, 'grasa,musculo,resistencia', 'principal', 'En puente, levanta una pierna estirada y sube la cadera con la otra.', 'ninguno', 'Glúteos · Isquiotibiales'),
  ('Flexiones abiertas', 'empuje', 2, 'grasa,musculo,resistencia', 'principal', 'Manos más separadas que los hombros, baja el pecho al suelo.', 'ninguno', 'Pecho · Hombros'),
  ('Flexiones declinadas (pies en silla)', 'empuje', 3, 'musculo', 'principal', 'Pies sobre una silla firme, manos en el suelo y baja el pecho.', 'casa', 'Pecho alto · Hombros · Tríceps'),
  ('Plancha a flexión', 'empuje', 2, 'grasa,musculo,resistencia', 'principal', 'Pasa de plancha en antebrazos a manos, y vuelve. Alterna el brazo que empieza.', 'ninguno', 'Tríceps · Hombros · Core'),
  ('Flexión hindú', 'empuje', 3, 'musculo,movilidad', 'principal', 'Desde V invertida, baja el pecho rozando el suelo y termina en cobra.', 'ninguno', 'Hombros · Pecho · Tríceps'),
  ('Remo con mochila', 'tiron', 1, 'grasa,musculo,resistencia', 'principal', 'Inclinado con la espalda recta, tira de una mochila con peso hacia el ombligo.', 'casa', 'Espalda · Bíceps'),
  ('Ángeles en el suelo', 'tiron', 1, 'musculo,movilidad', 'principal', 'Boca abajo, desliza los brazos de arriba hacia la cadera con los pulgares arriba.', 'ninguno', 'Espalda alta · Hombros'),
  ('Superman con brazos alternos', 'tiron', 2, 'grasa,musculo,resistencia', 'principal', 'Boca abajo, eleva brazo y pierna contrarios y alterna sin parar.', 'ninguno', 'Zona lumbar · Espalda · Glúteos'),
  ('Elevación de piernas', 'core', 2, 'grasa,musculo,resistencia', 'principal', 'Boca arriba, sube las piernas estiradas hasta 90° y baja lento sin tocar el suelo.', 'ninguno', 'Abdomen bajo'),
  ('Giro ruso', 'core', 2, 'grasa,musculo', 'principal', 'Sentado e inclinado atrás, gira el tronco tocando el suelo a cada lado.', 'ninguno', 'Oblicuos · Abdomen'),
  ('Tijeras abdominales', 'core', 2, 'grasa,musculo,resistencia', 'principal', 'Boca arriba con las piernas en el aire, cruza una sobre otra sin parar.', 'ninguno', 'Abdomen · Flexores de cadera'),
  ('Toques de talón', 'core', 1, 'grasa,musculo', 'principal', 'Boca arriba, hombros despegados, lleva la mano a cada talón de lado a lado.', 'ninguno', 'Oblicuos'),
  ('Escaladores cruzados', 'core', 2, 'grasa,resistencia', 'principal', 'En posición de flexión, lleva cada rodilla hacia el codo contrario.', 'ninguno', 'Oblicuos · Core · Cardio'),
  ('Saltar la cuerda (sin cuerda)', 'cardio', 1, 'grasa,resistencia', 'principal', 'Saltitos rápidos en puntas de pie girando las muñecas como con una cuerda.', 'ninguno', 'Pantorrillas · Cardio'),
  ('Talones al glúteo', 'cardio', 1, 'grasa,resistencia', 'principal', 'Trota en el sitio llevando los talones hacia los glúteos.', 'ninguno', 'Isquiotibiales · Cardio'),
  ('Sprint en el sitio', 'cardio', 2, 'grasa,resistencia', 'principal', 'Corre en el sitio lo más rápido posible moviendo fuerte los brazos.', 'ninguno', 'Piernas · Cardio'),
  ('Jumping jack con sentadilla', 'cardio', 2, 'grasa,resistencia', 'principal', 'Salta abriendo las piernas y baja a sentadilla sumo; salta y cierra.', 'ninguno', 'Piernas · Glúteos · Cardio'),
  ('Saltos de estrella', 'cardio', 3, 'grasa,resistencia', 'principal', 'Desde media sentadilla, salta abriendo brazos y piernas en forma de estrella.', 'ninguno', 'Cuerpo completo · Potencia'),
  ('El estiramiento más grande del mundo', 'movilidad', 1, 'movilidad', 'principal', 'En zancada baja, apoya la mano, gira el torso y abre el brazo al techo.', 'ninguno', 'Cadera · Columna · Hombros'),
  ('Círculos de cadera en 4 apoyos', 'movilidad', 1, 'movilidad', 'principal', 'En cuatro apoyos, dibuja círculos grandes con la rodilla hacia afuera.', 'ninguno', 'Cadera · Glúteos'),
  ('Bisagra de cadera', 'movilidad', 1, 'movilidad,musculo', 'principal', 'Rodillas suaves, lleva la cadera atrás con la espalda recta y vuelve a subir.', 'ninguno', 'Isquiotibiales · Glúteos · Zona lumbar'),
  ('Rotación de hombros en el suelo', 'movilidad', 1, 'movilidad', 'principal', 'De lado, rodillas dobladas, abre el brazo de arriba como un libro.', 'ninguno', 'Columna torácica · Pecho'),
  ('Estiramiento de glúteo (figura 4)', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'Boca arriba, cruza un tobillo sobre la rodilla contraria y acerca las piernas.', 'ninguno', 'Glúteos · Cadera'),
  ('Cobra suave', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'Boca abajo, apoya las manos y eleva el pecho despacio sin forzar la espalda.', 'ninguno', 'Abdomen · Columna'),
  ('Estiramiento de tríceps', 'movilidad', 1, 'grasa,musculo,resistencia,movilidad', 'enfriamiento', 'Lleva una mano a la espalda por detrás de la cabeza y empuja el codo suave.', 'ninguno', 'Tríceps · Hombros'),
  ('Hip thrust con barra', 'piernas', 2, 'musculo,grasa', 'principal', 'Espalda alta en un banco, barra sobre la cadera, sube apretando glúteos.', 'gimnasio', 'Glúteos · Isquiotibiales'),
  ('Zancadas con mancuernas', 'piernas', 2, 'musculo,grasa,resistencia', 'principal', 'Con una mancuerna en cada mano, da un paso al frente y baja. Alterna.', 'gimnasio', 'Cuádriceps · Glúteos'),
  ('Curl de bíceps con mancuernas', 'tiron', 1, 'musculo', 'principal', 'Codos pegados al cuerpo, sube las mancuernas hasta los hombros y baja lento.', 'gimnasio', 'Bíceps · Antebrazos'),
  ('Extensión de tríceps en polea', 'empuje', 1, 'musculo', 'principal', 'Codos pegados, empuja la barra de la polea hacia abajo hasta estirar los brazos.', 'gimnasio', 'Tríceps'),
  ('Aperturas con mancuernas', 'empuje', 2, 'musculo', 'principal', 'Acostado en el banco, abre los brazos con codos suaves y júntalos arriba.', 'gimnasio', 'Pecho · Hombros'),
  ('Elíptica a intervalos', 'cardio', 1, 'grasa,resistencia', 'principal', 'Pedalea en la elíptica a ritmo fuerte usando también los brazos.', 'gimnasio', 'Cuerpo completo · Cardio'),
  ('Farmer walk (caminata con pesas)', 'core', 2, 'grasa,musculo,resistencia', 'principal', 'Camina erguido con una pesa pesada en cada mano y el abdomen firme.', 'gimnasio', 'Core · Agarre · Hombros');

insert into public.recetas (nombre, tipo, objetivos, kcal, proteina, minutos, descripcion, ingredientes, pasos) values
  ('Arepa de maíz con huevos pericos', 'desayuno', 'grasa,musculo,resistencia,movilidad', 380, 18, 15, 'El clásico de la casa, con más huevo y menos aceite.', '["1 arepa de maíz mediana","2 huevos","1/2 tomate picado","2 cucharadas de cebolla larga","1 cucharadita de aceite"]'::jsonb, '["Asa la arepa en un sartén sin grasa.","Sofríe tomate y cebolla con la cucharadita de aceite.","Agrega los huevos batidos y revuelve hasta que cuajen.","Sirve los pericos sobre la arepa."]'::jsonb),
  ('Avena con banano y canela', 'desayuno', 'grasa,resistencia,movilidad', 330, 11, 10, 'Energía que dura toda la mañana.', '["1/2 taza de avena en hojuelas","1 taza de leche o bebida vegetal","1 banano","Canela al gusto"]'::jsonb, '["Cocina la avena con la leche a fuego medio 5 minutos.","Agrega el banano en rodajas.","Termina con canela."]'::jsonb),
  ('Batido de borojó con avena', 'desayuno', 'musculo,resistencia', 360, 14, 5, 'La fruta insignia del Chocó en versión desayuno.', '["1/2 taza de pulpa de borojó","1 taza de leche","3 cucharadas de avena","1 cucharadita de miel (opcional)"]'::jsonb, '["Licúa todo con hielo.","Tómalo recién hecho."]'::jsonb),
  ('Yogur con papaya y granola', 'desayuno', 'grasa,movilidad', 300, 13, 5, 'Fresco, rápido y suave para el estómago.', '["1 taza de yogur natural sin azúcar","1 taza de papaya picada","2 cucharadas de granola"]'::jsonb, '["Sirve el yogur en un bowl.","Agrega la papaya y la granola encima."]'::jsonb),
  ('Huevos revueltos con plátano cocido', 'desayuno', 'musculo,resistencia', 420, 16, 20, 'Plátano verde cocido en vez de frito: misma energía, menos grasa.', '["1/2 plátano verde","2 huevos","1 tajada de queso campesino","Sal y cebolla al gusto"]'::jsonb, '["Cocina el plátano en agua con sal 15 minutos.","Haz los huevos revueltos con cebolla.","Sirve con el plátano y el queso."]'::jsonb),
  ('Pescado sudado con arroz y ensalada', 'almuerzo', 'grasa,musculo,resistencia,movilidad', 540, 38, 30, 'Sabor del Pacífico, alto en proteína.', '["1 filete de pescado blanco (150 g)","1 tomate","1/2 cebolla","Cilantro y ajo","3/4 taza de arroz cocido","Ensalada de lechuga y pepino"]'::jsonb, '["Haz un hogao con tomate, cebolla y ajo.","Pon el pescado encima, tapa y cocina 12 minutos a fuego bajo.","Termina con cilantro.","Sirve con el arroz y la ensalada."]'::jsonb),
  ('Pollo a la plancha con patacón al horno', 'almuerzo', 'musculo,resistencia', 580, 42, 35, 'Patacón crocante sin freír.', '["1 pechuga de pollo (150 g)","1/2 plátano verde","Limón, ajo y sal","Ensalada de tomate y cebolla"]'::jsonb, '["Adoba el pollo con limón, ajo y sal.","Aplana el plátano cocido y hornéalo 20 minutos a 200 °C.","Cocina el pollo a la plancha 5 minutos por lado.","Sirve con la ensalada."]'::jsonb),
  ('Lentejas con arroz integral y aguacate', 'almuerzo', 'grasa,resistencia,movilidad', 520, 22, 40, 'Fibra y proteína vegetal que llenan de verdad.', '["1 taza de lentejas cocidas","1/2 taza de arroz integral","1/4 de aguacate","Hogao casero"]'::jsonb, '["Calienta las lentejas con el hogao.","Sirve con el arroz integral.","Agrega el aguacate en tajadas."]'::jsonb),
  ('Encocado ligero de pescado', 'almuerzo', 'musculo,resistencia', 610, 36, 35, 'El encocado de siempre con leche de coco rebajada.', '["1 filete de pescado (150 g)","1/2 taza de leche de coco + 1/2 taza de agua","Pimentón, cebolla y ajo","3/4 taza de arroz"]'::jsonb, '["Sofríe pimentón, cebolla y ajo.","Agrega la leche de coco rebajada y deja espesar 5 minutos.","Cocina el pescado en la salsa 10 minutos.","Sirve con arroz."]'::jsonb),
  ('Bowl de atún, arroz y verduras', 'almuerzo', 'grasa,musculo', 480, 34, 15, 'Para los días sin tiempo.', '["1 lata de atún en agua","3/4 taza de arroz","Zanahoria rallada","Pepino y tomate","Limón"]'::jsonb, '["Pon el arroz de base.","Agrega el atún escurrido y las verduras.","Aliña con limón y sal."]'::jsonb),
  ('Tortilla de huevo con verduras', 'cena', 'grasa,musculo,resistencia,movilidad', 390, 22, 15, 'Liviana y rápida.', '["3 huevos","Espinaca","Tomate","Cebolla","1 arepa pequeña"]'::jsonb, '["Saltea las verduras 2 minutos.","Agrega los huevos batidos y cocina tapado.","Sirve con la arepa."]'::jsonb),
  ('Sopa de verduras con pollo desmechado', 'cena', 'grasa,movilidad', 360, 28, 35, 'Reconfortante sin ser pesada.', '["100 g de pollo desmechado","Ahuyama, zanahoria, habichuela","1/2 papa","Cilantro"]'::jsonb, '["Cocina las verduras en agua con sal 20 minutos.","Agrega el pollo y deja 5 minutos más.","Termina con cilantro."]'::jsonb),
  ('Wrap de pollo y aguacate', 'cena', 'musculo,resistencia', 440, 32, 10, 'Se arma en minutos con el pollo del almuerzo.', '["1 tortilla integral","100 g de pollo","1/4 de aguacate","Lechuga y tomate"]'::jsonb, '["Calienta la tortilla.","Rellena con pollo, aguacate y verduras.","Enrolla y corta a la mitad."]'::jsonb),
  ('Pescado a la plancha con yuca cocida', 'cena', 'musculo,resistencia,grasa', 450, 34, 30, 'Proteína limpia y un carbohidrato de la región.', '["1 filete de pescado (130 g)","1 trozo de yuca (100 g)","Limón","Ensalada verde"]'::jsonb, '["Cocina la yuca en agua con sal hasta que ablande.","Haz el pescado a la plancha con limón.","Sirve con la ensalada."]'::jsonb),
  ('Ensalada de garbanzos', 'cena', 'grasa,movilidad', 400, 17, 10, 'Fría, fresca y con mucha fibra.', '["1 taza de garbanzos cocidos","Tomate, pepino y cebolla morada","Perejil","Limón y aceite de oliva"]'::jsonb, '["Pica las verduras.","Mezcla con los garbanzos.","Aliña con limón, una cucharadita de aceite y sal."]'::jsonb),
  ('Fruta picada con limón', 'snack', 'grasa,resistencia,movilidad', 140, 2, 5, 'Mango, piña o papaya de temporada.', '["1 taza de fruta picada","Zumo de limón"]'::jsonb, '["Pica la fruta y agrega el limón."]'::jsonb),
  ('Yogur natural con frutos secos', 'snack', 'musculo,resistencia,grasa', 250, 12, 2, 'Proteína y grasas buenas entre comidas.', '["1 vaso de yogur natural","1 puñado pequeño de maní o almendras"]'::jsonb, '["Sirve el yogur y agrega los frutos secos."]'::jsonb),
  ('Chontaduro con sal', 'snack', 'musculo,resistencia', 210, 3, 2, 'Energía del Pacífico, mejor sin miel.', '["3 chontaduros cocidos","Sal al gusto"]'::jsonb, '["Pela y sirve con una pizca de sal."]'::jsonb),
  ('Huevo cocido y mandarina', 'snack', 'grasa,musculo,movilidad', 150, 7, 10, 'Pequeño y fácil de llevar.', '["1 huevo cocido","1 mandarina"]'::jsonb, '["Cocina el huevo 10 minutos.","Acompaña con la mandarina."]'::jsonb),
  ('Batido de borojó (porción pequeña)', 'snack', 'musculo,resistencia', 200, 8, 5, 'Ideal después de entrenar.', '["1/4 taza de pulpa de borojó","1 vaso de leche","Hielo"]'::jsonb, '["Licúa y toma después de la sesión."]'::jsonb);

insert into public.consejos (categoria, texto) values
  ('hidratacion', 'Mantente hidratado. Con el calor del Pacífico tu cuerpo pierde más agua de la que crees.'),
  ('hidratacion', 'Ten una botella a la vista mientras entrenas: si la ves, la tomas.'),
  ('proteina', 'Incluye una fuente de proteína en cada comida: huevo, pescado, pollo, lentejas o yogur.'),
  ('proteina', 'El pescado de la región es de las proteínas más limpias y económicas que tienes cerca.'),
  ('porciones', 'Mitad del plato verduras, un cuarto proteína y un cuarto carbohidrato. Es la regla más simple que funciona.'),
  ('porciones', 'Cocina el plátano cocido o al horno en vez de frito: misma comida, mucha menos grasa.'),
  ('descanso', 'Dormir 7 a 8 horas también es entrenar: ahí es donde el músculo se recupera.'),
  ('descanso', 'Un día de descanso activo (caminar, estirar) ayuda más que no moverse nada.'),
  ('habitos', 'No busques perfección: si una comida no salió como querías, la siguiente es una nueva oportunidad.'),
  ('habitos', 'Prepara la proteína del día desde la mañana y evitarás comer lo primero que encuentres.'),
  ('azucar', 'Los jugos con azúcar suman calorías rápido. Prueba la fruta entera o el agua con limón.'),
  ('entreno', 'Come algo ligero 1 a 2 horas antes de entrenar: fruta, avena o una arepa pequeña.'),
  ('entreno', 'Después de entrenar, combina proteína y carbohidrato: por ejemplo, batido de borojó o huevo con fruta.');
